### ISSUE TITLE
Converting MBAC files to OBJ

### ISSUE THREAD

**Issue by Durik256** [j2me-preservation/MascotCapsule#7]
Hi, help me, I’ve been looking for information about editing ".mbac" for the third day now, all I found was exporting ".bac / .tra" to 3ds max, and converting them to ".mbac / .mtra" and viewing them but there is no reverse process, or at least conversion to ".obj". And I saw "tool / mbac2obj.py" with you, but I don’t understand how to use it, opening it gives an error in the blender, could you write a brief import instruction let's say "moodel.mbac" in a blender ???? thanks for earlier (my brains have already melted ...)

**Comment by minexew** [comment]
Do you have any experience with running Python programs? The utilities in this repository require a certain proficiency with the command line, they are not really targeted towards the "general public".

**Comment by Durik256** [comment]
> Do you have any experience with running Python programs? The utilities in this repository require a certain proficiency with the command line, they are not really targeted towards the "general public".


I need a very brief instruction, I can handle it)

**Comment by minexew** [comment]
Assuming you're on Windows:
- installed latest version of Python (default options should be fine)
- open the command line
- use the CD command to navigate to the directory where you have downloaded _mbac2obj.py_ (but download the entire repository, other files are needed by the script)
- execute `python mbac2obj.py <mbacpath> converted.obj`
(substitute `<mbacpath>` with the full path to your model file)
- if you are lucky and get no error, "converted.obj" will be generated next to the script, and you can load it into blender normally
- keep in mind that textures need to be matched manually, since the MBAC file does not contain any info about them

**Comment by Durik256** [comment]
Thanks a lot, everything turned out, I made a GUI shell for windows(https://github.com/Durik256/MBAC-to-OBJ). And through your scripts, can you convert .mbac and .mtra to fbx?

**Comment by Durik256** [comment]
> Assuming you're on Windows:
> 
> * installed latest version of Python (default options should be fine)
> * open the command line
> * use the CD command to navigate to the directory where you have downloaded _mbac2obj.py_ (but download the entire repository, other files are needed by the script)
> * execute `python mbac2obj.py <mbacpath> converted.obj`
>   (substitute `<mbacpath>` with the full path to your model file)
> * if you are lucky and get no error, "converted.obj" will be generated next to the script, and you can load it into blender normally
> * keep in mind that textures need to be matched manually, since the MBAC file does not contain any info about them

converts a little wrong(flip polygon and incorrect UV);
[https://i.ibb.co/vwpHpMS/export.png](url)

**Comment by minexew** [comment]
> Thanks a lot, everything turned out, I made a GUI shell for windows

Glad that you got it sorted out, and nice work on the tool!

> converts a little wrong(flip polygon and incorrect UV);

Ok, this is interesting! If you can send me the MBAC + texture, I will look into this. Perhaps there is some UV scaling necessary that is hard-coded somewhere outside the mbac file?

> And through your scripts, can you convert .mbac and .mtra to fbx?

I'm afraid not, for one because FBX is not an open format, but also because we haven't cracked MTRA yet, I believe.

> many files are not converted :(

If you tell me more about what the issue is, I can investigate.

**Comment by Durik256** [comment]
here is the link to the jar game : "https://drive.google.com/open?id=1RjBxe-r_Oj1DBZMMv0J-R17rk5-lpwDH" Many models cannot be converted from this game, including character models (pers_killer.mbac, etc.)! The model that incorrectly converted (UAZ1_00.mbac ant tx: t1.bmp). Thanks for answers)))

**Comment by minexew** [comment]
In the meantime, I'd recommend looking into this release instead: https://drive.google.com/open?id=1FqefgZKaK5qee14vx0-z0FIC9FzOTyb_; while targeting 176x220 instead of 240x320, it actually has textures in higher resolution (256x256) and no carrier branding. This is the one that I am working on and it seems we will be able to decode all the models and match textures.

**Comment by Durik256** [comment]
>
All the same, does not convert all models))

**Comment by minexew** [comment]
I have updated the scripts today, you can try again. 
Also have a look here: https://minexew.github.io/mbac-gallery/Stalker.html (not all models are textured, because at the moment I have to do the assignment one by one)

**Comment by Durik256** [comment]
everything works, cool)))

**Comment by minexew** [comment]
Great. I still haven't decided how to systematically deal with the model rotation (since it doesn't affect other games that I tested)
Also, if you can provide me with more model<->texture mappings, I will incorporate them and re-render the gallery. Eventually, I'd like to include other games as well.

**Comment by Durik256** [comment]
All model and texture https://drive.google.com/open?id=1LnMA9AIzWr5G3bU4VhrjaoL8fxobOgld

**Comment by minexew** [comment]
Cool, I guess I can extract texture names from the .mtl files?
(since what I really need are just the MBAC<->BMP pairings)

**Comment by minexew** [comment]
I have updated the gallery with your texture mappings and corrected model coordinate system.

**Comment by Durik256** [comment]
excellent work) in the models that I sent you, the coordinate system is also fixed)

**Comment by minexew** [comment]
I believe this is now resolved! :)

**Comment by minexew** [comment]
FWIW, this is the code I used to extract the texture names: https://gist.github.com/minexew/480984467fa374335581b6d833fb3817

**Comment by Scratchergames** [comment]
hey how i open a `.mbac` file? i dont know **HOW** i open it, i must convert it to `.obj`, *to use it*
- so i need help
- what tool i use
- how i convert it to obj files in [this game i found](https://prodigits.co.uk/pcontent/games/the-games4/240x320/3/pac-mankar_dzlmzjvw.jar) and my emulator cant run it

**Comment by KidGbzin** [comment]
> hey how i open a `.mbac` file? i dont know **HOW** i open it, i must convert it to `.obj`, _to use it_
> 
> * so i need help
> * what tool i use
> * how i convert it to obj files in [this game i found](https://prodigits.co.uk/pcontent/games/the-games4/240x320/3/pac-mankar_dzlmzjvw.jar) and my emulator cant run it

Give me the files and I can convert for you.

**Comment by Scratchergames** [comment]
>Give me the files and I can convert for you.

here is the `.jar` file, and inside the jar file here are the `.mbac` files in the folder Meshes, rename it to zip, extract it and go to the folder Meshes, i need Pacman, blinky, Pinky, inky and Clyde. So I Uploaded The Jar File (easy way) [pac-mankar_dzlmzjvw.jar](https://prodigits.co.uk/pcontent/games/the-games4/240x320/3/pac-mankar_dzlmzjvw.jar) or use this zip file (easiest way)
[Meshes.zip](https://github.com/user-attachments/files/23291384/Meshes.zip)

**Comment by Scratchergames** [comment]
@KidGbzin

ok so with those files, extract those `.mbpkg` (custom ZIP file) and i get the obj model to import in blender and the bones are that json right (source from the readme)

**Comment by minexew** [comment]
@KidGbzin as far as I'm concerned, it's not a problem to continue the
conversation here; it might even help someone else in the future

**Comment by Scratchergames** [comment]
i posted now (sorry if i posted 2 times)

**Comment by KidGbzin** [comment]
Here, every file extracted on each folder. All `.obj` and textures, just ignore `.mbac` and `.json` files. I store `.mbac` files for original reference, and `.json` if you want to create an armature. But since the game just move things globally and do just simple rotations in game runtime you won't need them. Old racing games just position and rotate the entire model to optimize space and CPU usage.

[Pac-Man Extracted.zip](https://github.com/user-attachments/files/24424954/Pac-Man.Extracted.zip)
